import Head from 'next/head'
import type {NextPage} from "next";

const Home: NextPage = () => {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app"/>
          <meta name="viewport" content="width=device-width, initial-scale=1"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className="min-h-screen bg-white">
          <div className="py-24 sm:py-32 lg:py-40">
            <div className="mx-auto max-w-7xl px-2 lg:px-4">
              <div className="mt-20 py-4 text-center">
                <p className="text-gray-400">Powered by</p>
                <a href="https://github.com/serhiyhvala" className='text-indigo-500 font-medium' target='_blank' rel='noreferrer'>Hvala Sergiy</a>
              </div>
            </div>
          </div>
        </div>
      </>
  )
}

export default Home
